// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEhcjkw5U5Jat4vbQ_O40SUuC2yFWUv90',
    appId: '1:548486440793:web:184096b1bb572d10b4ce48',
    messagingSenderId: '548486440793',
    projectId: 'cookbooksapp-8ef1c',
    authDomain: 'cookbooksapp-8ef1c.firebaseapp.com',
    storageBucket: 'cookbooksapp-8ef1c.appspot.com',
    measurementId: 'G-67J7L3KR3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXp0w5l6fKLQzVIJLw4zlZVDwC-drBu0',
    appId: '1:548486440793:android:c7078a262fe8f524b4ce48',
    messagingSenderId: '548486440793',
    projectId: 'cookbooksapp-8ef1c',
    storageBucket: 'cookbooksapp-8ef1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTHIPCIqYrmZpx45v7fY-Ht5GJpFQJELA',
    appId: '1:548486440793:ios:91362b97abc60aaeb4ce48',
    messagingSenderId: '548486440793',
    projectId: 'cookbooksapp-8ef1c',
    storageBucket: 'cookbooksapp-8ef1c.appspot.com',
    iosBundleId: 'te.labinformatica.cookbooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTHIPCIqYrmZpx45v7fY-Ht5GJpFQJELA',
    appId: '1:548486440793:ios:91362b97abc60aaeb4ce48',
    messagingSenderId: '548486440793',
    projectId: 'cookbooksapp-8ef1c',
    storageBucket: 'cookbooksapp-8ef1c.appspot.com',
    iosBundleId: 'te.labinformatica.cookbooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEhcjkw5U5Jat4vbQ_O40SUuC2yFWUv90',
    appId: '1:548486440793:web:b4b76b1c37e94e06b4ce48',
    messagingSenderId: '548486440793',
    projectId: 'cookbooksapp-8ef1c',
    authDomain: 'cookbooksapp-8ef1c.firebaseapp.com',
    storageBucket: 'cookbooksapp-8ef1c.appspot.com',
    measurementId: 'G-59MNJVF9X0',
  );
}
